/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VINCENT GINTING
 */
public class BeliFilm extends javax.swing.JFrame {

    /**
     * Creates new form BeliFilm
     */

    
    public BeliFilm() {
        initComponents();
        
    }
    
    
    public void setBetween(){                                                                                                                                   // Class , modifier(OOP 1)
        deskripsiBrg.setText("Anda telah membeli Film \" The In Between\"\n" +                                                          // Setter (OOP 2)
"Harga  : Rp 415.000,-\n" +
"Offers  : 10%\n" +
"Total   : Rp 373.500,-  ");
    }
    public void setBlackWidow(){
            deskripsiBrg.setText("Anda telah membeli Film \" Black Widow\"\n" +
"Harga  : Rp 315.000,-\n" +
"Offers  : 5%\n" +
"Total   : Rp 299.250,-  ");
        
        
    }
    public void setFreeGuy(){                                                                               //modifier public, class setFreeGuy
        deskripsiBrg.setText("Anda telah membeli Film \" Free Guy \"\n" +               //setter
"Harga  : Rp 350.000,-\n" +
"Offers  : 5%\n" +
"Total   : Rp 332.500,- ");
    }
    
    public void setNobody(){
        deskripsiBrg.setText("Anda telah membeli Film \" Nobody \"\n" +
"Harga  : Rp 250.000,-\n" +
"Offers  : 5%\n" +
"Total   : Rp 237.500,-  ");
    }
    
    public void setLostCity(){
        deskripsiBrg.setText("Anda telah membeli Film \" Lost City \"\n" +
"Harga  : Rp 350.000,-\n" +
"Offers  : 10%\n" +
"Total   : Rp 315.000,- ");
    }
    public void setMarryMe(){
        deskripsiBrg.setText("Anda telah membeli Film \" Marry Me \"\n" +
"Harga  : Rp 300.000,-\n" +
"Offers  : 0%\n" +
"Total   : Rp 300.000,- ");
    }
    
    public void setDeadPool(){
        deskripsiBrg.setText("Anda telah membeli Film \" DeadPool 2 \"\n" +
"Harga  : Rp 515.000,-\n" +
"Offers  : 15%\n" +
"Total   : Rp 473.250,-  ");
    } 
    
    public void setRebecca(){                           
        deskripsiBrg.setText("Anda telah membeli Film \" Rebecca  \"\n" +
"Harga  : Rp 250.000,-\n" +
"Offers  : 5%\n" +
"Total   : Rp 237.500,-  ");
    }
    
    public void setRed(){
        deskripsiBrg.setText("Anda telah membeli Film \" Turning Red \"\n" +
"Harga  : Rp 500.000,-\n" +
"Offers  : 0%\n" +
"Total   : Rp 500.000,-  ");
    }
    
    public void setRedNotice(){
        deskripsiBrg.setText("Anda telah membeli Film \" Red Notice \"\n" +
"Harga  : Rp 315.000,-\n" +
"Offers  : 10%\n" +
"Total   : Rp 183.500,-  ");
    }
    
    public void setSmart(){
        deskripsiBrg.setText("Anda telah membeli Film \" Get Smart \"\n" +
"Harga  : Rp 210.000,-\n" +
"Offers  : 20%\n" +
"Total   : Rp 168.000,- ");
    }
    
    public void setUncharted(){
        deskripsiBrg.setText("Anda telah membeli Film \" Uncharted \"\n" +                                              // Setter  (OOP 2)
"Harga  : Rp 259.000,-\n" +
"Offers  : 15%\n" +
"Total   : Rp 220.150,- ");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiBrg = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Pembelian Anda Telah Diproses!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 210, -1));

        deskripsiBrg.setEditable(false);
        deskripsiBrg.setColumns(20);
        deskripsiBrg.setRows(5);
        jScrollPane1.setViewportView(deskripsiBrg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 31, 259, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Terimakasih Telah Berbelanja di MovieHalal ! ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 113, 240, -1));

        jButton1.setText("Oke");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 133, 73, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\VINCENT GINTING\\Pictures\\me\\BG gradient.jpeg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea deskripsiBrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
