/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VINCENT GINTING
 */
public class PopUpRebecca extends javax.swing.JFrame {

    /**
     * Creates new form PopUpRebecca
     */
    public PopUpRebecca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Rebecca (2020)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 21, 200, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\tRebecca dibuka dengan latar tempat di Monte Carlo ketika karakter perempuan muda yang diperankan oleh Lily James masih \nbekerja sebagai asisten dari seorang wanita kaya. Di kota tersebut, dia pun bertemu dengan Maxim de Winter (Armie Hammer), seorang duda\nkaya raya yang memiliki tanah luas yang dinamakan Manderley.Keduanya pun semakin dekat setiap harinya dan akhirnya memutuskan untuk \nmelanjutkan hubungan mereka ke jenjang pernikahan. Sang wanita yang kini disebut sebagai Nyonya de Winter pun tinggal bersama dengan \nsuaminya di kediaman besar yang berada di wilayah Manderley. Namun, konflik mulai berdatangan ketika dia pindah ke kediaman tersebut dan \nmembuat hidup dari sang wanita enggak pernah tenang.\n\tPasalnya, Nyonya de Winter ‘dihantui’ oleh memori tentang Rebecca selaku mantan istri dari Maxim yang masih belum hilang \ndari ingatan sang suami. Kondisi pun diperparah dengan kehadiran Nyonya Danvers (Kristen Scott Thomas), pengurus kediaman Manderley \nyang kerap membangkitkan memori dari Rebecca.\n\tJalan cerita tersebut pun akan sangat menarik jika kalian belum pernah membaca novel aslinya ataupun versi film Rebecca \n(1940) yang disutradarai oleh Alfred Hitchcock. Apalagi, di balik plot tersebut kita disajikan dengan sejumlah plot twist yang cukup mengagetkan.\nNamun, buat kalian yang sudah pernah melihat versi Rebecca dalam adaptasi sebelumnya, film orisinal Netflix ini akan menjadi kurang berkesan.\nSoalnya, jalan ceritanya terbilang sama persis sehingga plot twist yang ada di dalamnya menjadi enggak mengejutkan karena sudah tertebak.\nApalagi, Rebecca yang disutradarai Ben Wheatley ini ‘dihantui’ oleh versi Alfred Hitchcock yang berhasil meraih “Best Picture” di Oscar.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 725, 209));

        jLabel2.setText("Price : Rp 250.000,-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, 110, -1));

        jLabel3.setText("Offers 5%");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 283, -1, -1));

        jLabel4.setText("Romance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 283, 60, -1));

        jButton1.setText("Beli");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 279, 73, -1));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 279, 73, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\VINCENT GINTING\\Pictures\\me\\BG Rebecca fix no debat.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BeliFilm main = new BeliFilm ();
        main.setRebecca();
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Beranda main = new Beranda();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpRebecca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpRebecca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpRebecca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpRebecca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpRebecca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
